### ISSUE TITLE
When forced to a specific language other than English, will instead display "English" as current language

### ISSUE THREAD

**Issue by PhilLB1239** [UWPCommunity/Quick-Pad#101]
**Description**
When forcing a specific language other than English (United States), when the app is relaunched and displayed at the desired language, the same option will display "English" instead of the current language (see screenshot).
![image](https://user-images.githubusercontent.com/51797038/63904884-6b34f200-c9e0-11e9-8aea-8592b522c64b.png)

**To reproduce the issue:**
1. Launch Quick Pad settings page
2. Set language to anything other than English (in my case, French (Canada))
3. Restart app
4. Launch Quick Pad settings page
5. Notice the issue

**Comment by yaichenbaum** [comment]
Thanks for reporting, I am closing this issue since the feature is completed now. The build you have was still a beta version. If you run from the source code it displays correctly.
