### ISSUE TITLE
New advanced tab in setting idea.

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#120]
This is just an idea I had and not at all final. Here is the pitch.

**A brand new 'Advanced' tab in settings for power users**
- [x]  Paste with no format.
- [x] https://github.com/UWPCommunity/Quick-Pad/issues/129
- [x]  Reset settings.
- [x]  Export settings (can be used for debug proposes as well.
- [x]  Import settings.
- [x]  Crash history (for debugging as well).

**Comment by stephen-haxby** [comment]
7. Paste with no format

**Comment by yaichenbaum** [comment]
- [ ] 1. Shadow on find and replace needs to follow the setting as well.
![image](https://user-images.githubusercontent.com/39923744/64705364-d6210700-d47d-11e9-965b-c7bee69207a5.png)

**Comment by yaichenbaum** [comment]
@stephen-haxby your request has been added to the dev branch, once this update is ready it will go out for testing. I will make sure to let you know when that is.
