### ISSUE TITLE
Icon for Each File Extension

### ISSUE THREAD

**Issue by Henboy10** [UWPCommunity/Quick-Pad#128]
I keep going back and forth between this app and [Notepads](https://www.microsoft.com/store/productId/9NHL4NSC67WM). One feature that I love from Notepads is the modern, yet minimalistic icons that adapt to the file type. See the image below for an example. I wish Quick Pad had the same for .txt and .rtf

![image](https://user-images.githubusercontent.com/22181579/64293058-6e286900-cf31-11e9-9bd6-3a75c80714d3.png)

**Comment by yaichenbaum** [comment]
Is that image from Notepads or just a mock-up you made?
@ray1997 actually came up with a concepts yesterday for something like this and I am strongly considering it.
![image](https://user-images.githubusercontent.com/39923744/64299222-54455100-cf46-11e9-9087-55046ef10c20.png)

Also just because you mentioned it, I use Notepads as well, the developer did a great job and actually helped me with some parts of Quick Pad.

**Comment by Henboy10** [comment]
The image that I included is actually from Notepads. I think the icons from @ray1997 are great options. Although in my opinion, something seems off...

I'm not a designer, but what if the paper on the pad was white and then whatever is written on the paper itself is blue. Here is something that I sloppily threw together as a concept.
![concept](https://user-images.githubusercontent.com/22181579/64300623-26124200-cf43-11e9-9858-6b6609fd5d08.png)

**Comment by yaichenbaum** [comment]
Yeah, the icons were just concepts. I will explore more for better ideas. The issue with adding those lines is it doesn't scale down so well to smaller sizes.

**Comment by Henboy10** [comment]
That's a good point. I think whatever we end up choosing for the miscellaneous icons need to somehow fit well with icons from other programs. We don't want it to stick out too much, otherwise, it won't look right.

I think it's fine if the main icon stands out, but the txt/rtf icons should be a little more subtle.

Do with that what you will 😁

**Comment by yaichenbaum** [comment]
I hope to draw up several ideas soon. Will share here when they are ready.

**Comment by yaichenbaum** [comment]
Here is idea 1 
![image](https://user-images.githubusercontent.com/39923744/64302859-5366ec00-cf53-11e9-9b1f-1cd14d152a88.png)

**Comment by yaichenbaum** [comment]
And the same idea just with different colors. 
![image](https://user-images.githubusercontent.com/39923744/64302980-e011aa00-cf53-11e9-952d-db4fd9100ce0.png)

**Comment by Henboy10** [comment]
I like your single sheet idea, especially your white variant. The explanation behind the design is great too. 

**I'm thinking out loud here, bare with me🤣**
I feel like this design kinda makes it unidentifiable as a piece of paper, though. With the main app icon, the three layers of paper gave it depth making it identifiable as a notepad. I'd be interested to hear if you think the same thing. 

What if you (or anyone) could design a simple/fluent design notepad with the page flipped back? I think that would give the idea of a single document. That may not be a viable option; I thought I'd just throw that out there
![MVIMG_20190904_205713](https://user-images.githubusercontent.com/22181579/64305941-ad1ce580-cf56-11e9-86ae-cbf2f04a9250.jpg)

**Comment by yaichenbaum** [comment]
I can do that, I just wanted to keep it different then Notepads since I cannot exactly copy it 😀 but I will explore doing it.

**Comment by Henboy10** [comment]
Here is a real-world representation of what was in my head, could be based on something of this sort. Wrapping a page back behind the notepad.
![image](https://user-images.githubusercontent.com/22181579/64306441-5fa17800-cf58-11e9-87f9-c6cf4af86528.png)

I'm interested to see all of the designs you can come up with. I'm not a good designer, so the best I can do is share with you ideas. You can make everyone's ideas look good.👍

**Comment by yaichenbaum** [comment]
I feel that would be better for an app icon itself. I am not sure how I can make that more a simple design which I am aiming for with this. I might just need to have a bent corner but when I get a chance I will try out both possibilities.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64354460-7cc45e00-cfcd-11e9-947a-fd9dc62be16f.png)

**Comment by yaichenbaum** [comment]
@Henboy10 any thought on the last concept I shared?

**Comment by Henboy10** [comment]
I think that maybe the txt tag is a little too small.
The problem that we've run into is that the design from _Notepads_ is so good that it's difficult not to make it too similar.
The challenge is going to be making something equally as good. We can do it, but it will take a lot of brain power

**Comment by Henboy10** [comment]
I think that maybe the one from _Notepads_ looks more like Material Design than it does Fluent Design. Is there any way to make a more "Fluent-y" design without using transparent acrylic?

**Comment by yaichenbaum** [comment]
I am not sure, I will try some more ideas. If you have any feel free to share them as well.

**Comment by Henboy10** [comment]
I'll try making concept designs myself, although, I have more experience with the photo editing side of Photoshop than I do with logo/icon design. They may not look great, but I can give it a shot.

**Comment by yaichenbaum** [comment]
I am liking this idea
![image](https://user-images.githubusercontent.com/39923744/64647872-d53d9600-d3e7-11e9-9660-355a57a502e9.png)

**Comment by Henboy10** [comment]
I like that too!

**Comment by yaichenbaum** [comment]
Working on adding them in right now!

**Comment by yaichenbaum** [comment]
Closing this issue since I will be working on new icons and tweaks as time goes on. The changes are live in the dev branch.
