### ISSUE TITLE
Option to automatically open in different modes depending on the file type.

### ISSUE THREAD

**Issue by Henboy10** [UWPCommunity/Quick-Pad#129]
For example if you open up a .txt file with Quick-Pad, it should open up in classic mode automatically. If you open up .rtf it would ideally open up in the default mode.
This setting should be under the advanced tab #120

**Comment by yaichenbaum** [comment]
I am afraid this behavior would clash with users choosing default launch mode. Perhaps we can have a automatic mode that chooses based on the file type.
Another way is to have separate launch mode settings when just opening the app and another setting to automatically choose the mode when launching from a file.

**Comment by Henboy10** [comment]
I love your idea on the option for an auto mode.

**Comment by yaichenbaum** [comment]
Changes are in dev. They will come to the store with the next update.
