### ISSUE TITLE
Translation thread

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#163]
In order to keep track of when there are new strings to translate or strings that need to be updated, I am creating this issue for translators to follow.

**Comment by yaichenbaum** [comment]
@ray1997 @PhilLB1239 @FJduFou adding you to this thread. If you dont want to get notifications just hit unsubscribe. Thank you.

**Comment by ray1997** [comment]
I'd say, next time if there's multiple PR merge wanted to update translation. Take my PR first and override it with translator's submitted PR.

**Comment by yaichenbaum** [comment]
@ray1997 Sure.

**Comment by yaichenbaum** [comment]
**Version 4.3.15**
- [ ] [th-TH][Thai]
- [ ] [fr-CA][French]
- [ ] [es][Spanish]
- [ ] [ar-SA][Arabic]
- [ ] [fr-FR][French]
- [ ] [it][Italian]

**Comment by yaichenbaum** [comment]
**Version 4.3.16**
- [ ] [th-TH][Thai]
- [ ] [fr-CA][French]
- [ ] [es][Spanish]
- [ ] [ar-SA][Arabic]
- [ ] [fr-FR][French]
- [ ] [it][Italian]

**Comment by themoiFR** [comment]
There are some french translations that are not very french :
- Size Up -> "Augmenter la taille"
- Size Down -> "Diminuer la taille"

![image](https://user-images.githubusercontent.com/57669556/68681338-83d69200-0563-11ea-8969-5ecefeb8d950.png)

In french it is better to write "Afficher" than "Montrer"

There is a missing Translation for "Show Left Align" -> "Afficher l'alignement à gauche"

Maybe specify "show ..." isn't really useful because there is already the 'check' icon to says that...

**Comment by yaichenbaum** [comment]
@FJduFou can you check this out?

**Comment by themoiFR** [comment]
Also the translation for the auto saving time should be "Intervalle de sauvegarde automatique :"

**Comment by yaichenbaum** [comment]
I decided we are not yet ready for new strings, first I will send out an update to beta testers for some through testing and only then will we do the new strings.
Thank you for all your help on Quick Pad!

**Comment by FJduFou** [comment]
@yaichenbaum yes ?

**Comment by yaichenbaum** [comment]
We are working on a rewrite of the app that should be ready for localization in a week or two, until then there will be nothing to update.

**Comment by FJduFou** [comment]
Oki, yhis require retranslate all ?

**Comment by yaichenbaum** [comment]
Unfortunately it will, I am really sorry about this/

**Comment by FJduFou** [comment]
oki, no problem 👌

**Comment by yaichenbaum** [comment]
The rewrite is ready for new strings! Please make sure you are working off the refactor branch.

**Comment by PhilLB1239** [comment]
@themoiFR Yeah, made those translations. Will improve it for the rewrite.

**Comment by yaichenbaum** [comment]
At the moment I haven't added back the options to hide buttons in the toolbar. It's possible I will add it back later on and I will definitely think about the word "show" over there.

**Comment by FJduFou** [comment]
![image](https://user-images.githubusercontent.com/46401854/69979991-a1c65f80-152f-11ea-87ba-ccb6204e1fbf.png)
![image](https://user-images.githubusercontent.com/46401854/69980091-d20dfe00-152f-11ea-8714-9ba5b70424c2.png)

**Comment by yaichenbaum** [comment]
All the strings for the rewrite should be added in to the app, I would appreciate if you could translate the remaining ones so I can get a final build for the rewrite in testing.

**Comment by yaichenbaum** [comment]
There are some new strings in the `develop` branch ready to be translated, ar-EG and es are already up to date.
