### ISSUE TITLE
Blue or dark splash screen ?

### ISSUE THREAD

**Issue by FJduFou** [UWPCommunity/Quick-Pad#167]
Hi,
After a discussion about this pull request #160  with @yaichenbaum , we wondered if you prefer a **blue** or **dark** home screen?
That's why we ask you to give your opinion (more **blue** or conversely, **darker**)
You can compare the results below:
**blue**:
![2019-10-17](https://user-images.githubusercontent.com/46401854/67037763-6fe37000-f11e-11e9-9f52-9fa2397525b8.png)
or **dark**:
![2019-10-17 (6)](https://user-images.githubusercontent.com/46401854/67037764-6fe37000-f11e-11e9-9fd7-2ae3ead707e0.png)

This will only affect the splash screen, whatever theme options you choose will still take take affect.

thank you in advance

**Comment by yaichenbaum** [comment]
I personally prefer blue but this is up to you 😊

**Comment by ray1997** [comment]
I kinda like a dark splash screen, even though we only get a chance to see it only a few seconds.
@yaichenbaum your app subscribed to store service. You could use that menu to ask existing users to go here.
https://partner.microsoft.com/dashboard/notificationgateway/notifications/table

**Comment by yaichenbaum** [comment]
Notifications is something you need to really think through before sending one. I have done it once or twice with big updates but you dont want to go over a few times a year since some users just want to get work done and not send feedback.

**Comment by ray1997** [comment]
right...

**Comment by FJduFou** [comment]
Dark win, thank you @yaichenbaum for authorizing the survey
