### ISSUE TITLE
Translation of the Store page

### ISSUE THREAD

**Issue by FJduFou** [UWPCommunity/Quick-Pad#175]
Currently, the page is in English, so I propose to other translators to put their translation here and thus centralized to allow better management
Store page: https://www.microsoft.com/en-us/p/quick-pad-uwp-notepad/9pdlwqhtlsv3

**Comment by FJduFou** [comment]
fr-fr {description}
Quick Pad facilite la prise de notes. La superposition compacte vous permet de garder l'application au-dessus d'autres fenêtres telles que Microsoft Edge, de sorte que vous puissiez continuer à prendre des notes sans basculer entre elles.
La sauvegarde automatique garantit que votre travail est enregistré et où vous le souhaitez.
Si vous souhaitez utiliser le même style que le bloc-notes classique intégré à Windows, Mode Classique a la même disposition mais ajoute des éléments de design agréables à regarder.
S'il vous plaît examiner Quick Pad, nous apprécions vraiment vos commentaires et nous sommes impatients de vous voir bientôt. Prendre plaisir!

**Comment by yaichenbaum** [comment]
Release notes have been updated,
> Here is whats new in 4.3.96
> • Quick Pad has been rewritten from scratch!
> • Added support for setting the default encoding.
> • Improved the design and layout.

**Comment by FJduFou** [comment]
Voici les nouveautés dans la 4.3.96
• Quick Pad a été réécrit à partir de zéro!
• Ajout de la prise en charge de la définition de l'encodage par défaut.
• Amélioration de la conception et de la mise en page.

**Comment by PhilLB1239** [comment]
Hold on, is there a way to contribute for the store page's translation as well?

**Comment by yaichenbaum** [comment]
@PhilLB1239 There is 🙂

**Comment by PhilLB1239** [comment]
@yaichenbaum So, we just paste the translation here or do you provide a file for me to edit?

**Comment by yaichenbaum** [comment]
You can just paste it here, in order to keep this issue clean I delete comments from time to time so don't worry if you see something go missing.

**Comment by PhilLB1239** [comment]
_oh no something is missing_

I am busy right now, but I will translate the page later, sounds good?

**Comment by yaichenbaum** [comment]
The store description can be updated any time so its no rush, its the in-app ones that are more important since those are tied to a release.

**Comment by PhilLB1239** [comment]
**French (Canada) version of the Store description**

> Quick Pad rend les prises de note facile. Les fonctionnalités telles que le mode superposé vous permet de garder l’application par-dessus d'autres fenêtres et être plus productif. Elle inclut aussi plusieurs fonctionnalités utiles comme le sauvegarde automatique, mode focus et la prise en charge des fichiers en texte riche.
Quick Pad inclut aussi plusieurs options pour personnaliser le visuel et la sensation ainsi que plusieurs options de thèmes.

**Comment by Slevilex** [comment]
Quick Pad - Akıcı Not Defteri

Quick Pad not almayı kolaylaştırıyor. Az yer kaplayan arayüz uygulamayı diğer pencerelerin üstünde tutup üretken olmanıza yardımcı oluyor. Bu uygulama otomatik kayıt, odaklanma modu ve .rtf (zengin metin belgesi) desteği gibi faydalı özellikler içeriyor.
Quick Pad görünümü özelleştirmek için bir sürü ayar ve çeşitli temalar sunuyor.

Turkish
I can translate the whole app too. Contact me please: sametahmetsahin1212@gmail.com

**Comment by yaichenbaum** [comment]
@Slevilex See this [doc](https://github.com/UWPCommunity/Quick-Pad/blob/develop/docs/TRANSLATOR.md ) about translating the app.

**Comment by Slevilex** [comment]
Unfortunately, I use Linux and I have to work on the text directly.

**Comment by Slevilex** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
It is possible to do that, just copy one of the existing xlf files from another language and change the relevant information to target the correct language.

**Comment by Slevilex** [comment]
@yaichenbaum Can you send me an example language for me to directly translate?

**Comment by yaichenbaum** [comment]
@Slevilex Sure, take a look at [this ](https://github.com/UWPCommunity/Quick-Pad/blob/develop/src/QuickPad.UI/QuickPad.UI/MultilingualResources/QuickPad.UI.fr-CA.xlf)one.

**Comment by Slevilex** [comment]
@yaichenbaum Thank you, I will start translating soon.

**Comment by MuMDevelopment** [comment]
Here a German version of the Store page:

### Description

> Quick Pad macht das Notieren leicht. Mit Funktionen wie Fenster-in-Fenster lassen Sie Quick Pad immer im Vordergrund und können produktiver arbeiten. Quick Pad enthält nützliche Funktionen wie das automatische Speichern, einen Fokusmodus und die Unterstützung für Rich Text Dateien. Das Erscheinungsbild der Anwendung kann mit vielen Optionen und vielen verschiedenen Farbthemen Ihren Wünschen angepasst werden. 

### What's new in this version

> Das ist neu in Version 4.3.97
	- Quick Pad wurde von Grund auf neu programmiert
	- Unterstützung für das standardmäßige  festlegen einer bestimmten Kodierung hinzugefügt
	- Design und Layout verbessert

### Features

> Fenster-in-Fenster Modus
Klassischer Modus
Automatisches Speichern
Dunkler Modus
Emojis

**Comment by yaichenbaum** [comment]
Moving forward, translations of the store page should be added to #163.
