### ISSUE TITLE
Add "Search on Bing" to context menu

### ISSUE THREAD

**Issue by sharpninja** [UWPCommunity/Quick-Pad#187]
**Describe the solution you'd like**
When showing the context menu, if there is text highlighted, provide an option to search for the text on Bing.

**Comment by dmarciano** [comment]
Would this specifically be for Edge/Bing or would it use the user's default browser/search engine?  For example, I prefer Chrome so if this feature was available, I would rather Chrome open and the search be performed via Google, but someone else might prefer Edge/Bing, or Firefox/Google, etc.

**Comment by sharpninja** [comment]
Default browser, of course.  But would definitely prefer Bing here.  You could make it an option I guess, but damn, the search results are so much better on Bing.

**Comment by dmarciano** [comment]
I personally feel that Google's results are far supior, but that is just my opinion.  However, I think maybe the best way to go would be to give them an option of several search engines and it would use that via their default browser.

**Comment by sharpninja** [comment]
> I personally feel that Google's results are far supior, but that is just my opinion. 

We shall have to agree to disagree.

**Comment by yaichenbaum** [comment]
The option to search with Bing is already implemented in classic mode, what this feature request is asking is to add it to the right click context menu as well.
Right now the search results will open in the default browser, however the search results will go through Bing. What I can do is see if it can be set to use whatever search engine you use in your browser.

**Comment by ahmed605** [comment]
I will work on this
