### ISSUE TITLE
Changing the size with the button "Size Up"

### ISSUE THREAD

**Issue by themoiFR** [UWPCommunity/Quick-Pad#189]
**Describe the bug**
The font size doesn't change properly with buttons size 

**To Reproduce**
1. Type some text,
2. Select the typed text,
3. Click on the "Size UP" button,
4. The size of the selected text is reduced or increased.

**Expected behavior**
Just change the font size of the selected text.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 19018.1]
 - App version: [v4.3.15.0]

**Additional context**
This is a permanent problem

**Comment by yaichenbaum** [comment]
Thank you for reporting this bug, this should now be fixed in the dev branch.
