### ISSUE TITLE
Keyboard shortcuts are not working when focus mode is set as the launch mode

### ISSUE THREAD

**Issue by themoiFR** [UWPCommunity/Quick-Pad#190]
**Is your feature request related to a problem? Please describe.**
When you are in focus mode, and you want to save your file, you have to quit focus mode and save the file.

**Describe the solution you'd like**
Just do a CTRL-V to save (for exemple)...

**Comment by yaichenbaum** [comment]
You should already be able to use ctrl + s to save. Let me know if that helps.

**Comment by themoiFR** [comment]
That right but not when I do :
1. Open QuickPad
2. Write something
3. Go to focus mode
4. CTRL-S
5. Nothing append

**Comment by yaichenbaum** [comment]
What version of app are you running? I am having trouble reproducing this on my end.

**Comment by themoiFR** [comment]
V4.3.15.0

**Comment by yaichenbaum** [comment]
What is your default launch mode?

**Comment by themoiFR** [comment]
Focus

**Comment by yaichenbaum** [comment]
Ok, this really comes down to a whole refactor that is planned. With the planned code structure, it should fix this issue and many other smaller bugs as well.

**Comment by Henboy10** [comment]
I am having this same problem with the default launch mode. I open the app, and the keyboard shortcuts don't work.

**Comment by Henboy10** [comment]
After further messing with it, the commands seem to only work within the app. For example, if I copy something in the app, and try to paste it in Chrome, it won't work. But if I copy something in the app, I can paste it in the app.

The save command seems to not work when the default mode is set to focus.

I don't really know how else to describe it :)

**Comment by yaichenbaum** [comment]
@Henboy10 What you are describing is a known bug that the text is being copied as rich text and Chrome does not support rich text. If you try pasting it in Microsoft Word you will see that it works just fine. As a temporary work around while we work on fixing this issue you can go to Quick Pads settings, navigate to the advanced settings page and select "Keep text only".

**Comment by yaichenbaum** [comment]
This should be fixed in the rewrite which should be rolling out sometime in December.
