### ISSUE TITLE
Add option to open files

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#196]
Should support,
- [x] Dragging file in from File Explorer
- [x] From the menu bar (File > Open)
- [x] From the command bar
- [x] Ctrl + O
- [x] Command Line
- [x] Opening the app from a file.

**Comment by sharpninja** [comment]
This is a very good way to define your requirements.

**Comment by ahmed605** [comment]
I will work on the command line support

**Comment by ahmed605** [comment]
https://github.com/UWPCommunity/Quick-Pad/pull/294
