### ISSUE TITLE
Add find and replace

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#2]
Find and replace option.

**Comment by yaichenbaum** [comment]
This has been added, we will tweak and improve it as necessary before releasing to everyone.

**Comment by yaichenbaum** [comment]
- [ ] Add rounded corners to match the rest of the UI (sorry folks)
- [ ] Focus on the search text box when the UI is launched.
- [ ] Fix crash if you search for nothing.

**Comment by yaichenbaum** [comment]
Should we move the check boxes to be on the same line?
![image](https://user-images.githubusercontent.com/39923744/63657201-b2b34800-c76c-11e9-9d66-1e747927212a.png)

**Comment by ray1997** [comment]
@yaichenbaum For a better multilingual support. Let's assume that some language "Match case" might be long enough that putting the check boxes on same line might not be enough

**Comment by yaichenbaum** [comment]
Are you sure that its not wide enough to include most cases?

**Comment by yaichenbaum** [comment]
Since all the issues in this list have been addressed I will be closing this issue, if there are any bugs or other issues someone finds they should open a separate issue for the specific thing they found. Major thanks to @ray1997 for all the work and effort he put in to this.
