### ISSUE TITLE
Create SettingsViewModel class

### ISSUE THREAD

**Issue by sharpninja** [UWPCommunity/Quick-Pad#204]
- [x] Launch Mode
- [x] Locality Selection
- [x] Default File Type
- [x] Default Encoding
- [x] Autosave Enabled
- [x] Autosave Frequency

**Comment by themoiFR** [comment]
Can I do this one ?

**Comment by yaichenbaum** [comment]
@themoiFR Go ahead 😃

**Comment by themoiFR** [comment]
Is there a way to discuss with you with out spamming the discussion ?

**Comment by sharpninja** [comment]
> Is there a way to discuss with you with out spamming the discussion ?

I am on the discord quick-pad-dev channel right now.

**Comment by themoiFR** [comment]
can you invite me on discord ? 😉

**Comment by yaichenbaum** [comment]
That channel is private, I would recommend using the appropriate issues here. You can also create new issues if needed.

**Comment by themoiFR** [comment]
I do the xaml of the settings too ?

**Comment by sharpninja** [comment]
The Xaml is written, but needs to have the ViewModel applied to it.

**Comment by yaichenbaum** [comment]
The Xaml for the settings page has not been written yet. The plan is to use the same settings design as the current version but it will need to be rewritten and broken up in to separate pages as opposed to it all being stuffed in to one Xaml file.

**Comment by themoiFR** [comment]
OK I will see what I can do

**Comment by yaichenbaum** [comment]
I finished adding in the Xaml for settings, it should be pretty simple to start work on this task now.

**Comment by themoiFR** [comment]
yes it is thanks
