### ISSUE TITLE
Status text color should be SystemControlForegroundBaseMediumHighBrush by default

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#241]
The color of the status text on the status bar should be `SystemControlForegroundBaseMediumHighBrush` by default.

**Comment by sharpninja** [comment]
Updated.  Will checkin tonight.

**Comment by yaichenbaum** [comment]
@sharpninja Was this checked in yet?

**Comment by sharpninja** [comment]
Done.
