### ISSUE TITLE
Change "Untitled" to the localization

### ISSUE THREAD

**Issue by FJduFou** [UWPCommunity/Quick-Pad#253]
Translate the title bar (Untitled) in language of the localization.
Exemple: "Sans titre" fo fr-fr
![image](https://user-images.githubusercontent.com/46401854/69836186-80bbf100-1247-11ea-8926-3127d3f13194.png)

**Comment by sharpninja** [comment]
Added translation in en-US resources file.  Will check in tonight.

**Comment by FJduFou** [comment]
thx

**Comment by sharpninja** [comment]
Done.
