### ISSUE TITLE
Copied text should still be available after closing the app

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#256]
Copied text should still be available after closing the app

**Comment by sharpninja** [comment]
Please research if a permission is needed.  I've set the code appropriately but it doesn't work.

**Comment by yaichenbaum** [comment]
A permission is not necessary. @Leisvan Do you still have that code you shared with me for this?

**Comment by Leisvan** [comment]
Yes. I'll send you the code later.
