### ISSUE TITLE
Should ask to save if the user has an open file in the following cases

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#258]
If the user has unsaved changes and they
- [x] Drag a file in
- [x] Open File Command
- [x] New Document Command
- [x] Close Command

**Comment by sharpninja** [comment]
Done

**Comment by yaichenbaum** [comment]
How can this be done if first one isn't even possible yet? Do you mean as soon as drag to open is implemented the work is already in place?

**Comment by sharpninja** [comment]
Don't know what you mean about one not being possible.
________________________________

**Comment by yaichenbaum** [comment]
At the moment Quick Pad does not support dragging files in from file explorer.

**Comment by sharpninja** [comment]
Drag to open is done.
________________________________

**Comment by yaichenbaum** [comment]
I just checked and it doesn't ask to save changes if I drag a file in.

**Comment by sharpninja** [comment]
OK, don't know where the original code went, but it's fixed again.
