### ISSUE TITLE
Ask to save dialog missing translations.

### ISSUE THREAD

**Issue by FJduFou** [UWPCommunity/Quick-Pad#274]
**Translation error**
Don't have translation

**Screenshots**
![image](https://user-images.githubusercontent.com/46401854/70470223-d9eb1680-1aca-11ea-97e3-830f9a6bc317.png)
(Exit if don't save)

**Comment by yaichenbaum** [comment]
Do you have any better ideas for the last comment in your report?

**Comment by FJduFou** [comment]
![image](https://user-images.githubusercontent.com/46401854/70471996-a1e5d280-1ace-11ea-97e4-fb8d1693b41c.png)
(for exemple)

**Comment by yaichenbaum** [comment]
I don't really like that UI concept so much...

**Comment by FJduFou** [comment]
![image](https://user-images.githubusercontent.com/46401854/70472187-fa1cd480-1ace-11ea-958f-fb5394626c6c.png)
(or this of you like geometry)

**Comment by yaichenbaum** [comment]
The find feature has translations, it looks like you need to do the strings for it to display.

**Comment by yaichenbaum** [comment]
The Go To dialog isn't showing translations either.

**Comment by yaichenbaum** [comment]
This should be fixed with the next update, please reopen if you find its still an issue.
