### ISSUE TITLE
Switching display mode or setting default mode crashes app

### ISSUE THREAD

**Issue by Jonatz** [UWPCommunity/Quick-Pad#303]
Switching display mode or setting default mode crashes app. After setting the default mode to overlay and restarting the app, the app actually launches in overlay mode. In this state, it is impossible to switch back to other modes, because the UI switch button doesn't work anymore. Resetting the app through system settings fixes this, but it is replicable.

**Comment by yaichenbaum** [comment]
@Jonatz Thank you for opening this issue, can you provide a little more information such as which version number the app is and exactly which modes crash the app when setting them as default?

**Comment by Jonatz** [comment]
@yaichenbaum I'm on version 4.3.89.0 (beta, I guess). It seems to crash only when being set to overlay mode. Switching the default mode to other modes seems to before that seems to make it robust. I couldn't make out the exact pattern but switching default mode to overlay after a reset almost always crashes it.

**Comment by Jonatz** [comment]
@yaichenbaum I just received an update to 4.3.91.0. The app doesn't crash anymore, when setting the launch mode to overlay. By testing this I encountered a secondary bug: When launching into overlay mode and clicking the mode change button, the app switches to a hybrid mode. It looks like focus mode, but there is no back button in the upper left corner but the symbol for mode switching. Unfortunately the button doesn't seem to work. Relaunching the app doesn't fix it, only resetting does but the bug is replicable.

**Comment by yaichenbaum** [comment]
@Jonatz Thanks for the update, that bug is something I can reproduce, as of now a workaround is ctrl + shift + 1 to get out of that "hybrid mode". We will take a look about fixing this as soon as posible.

**Comment by yaichenbaum** [comment]
@ahmed605 Do you want to take a look to see if you can figure this out?

**Comment by yaichenbaum** [comment]
I managed to get it working for setting to launch in Compact Overlay Mode however I still need to fix setting it to focus mode.

**Comment by yaichenbaum** [comment]
I have a fix and it should roll out with the next update, please reopen this issue if it still occurs on future versions.

**Comment by yaichenbaum** [comment]
@Jonatz Can you update to the latest version and confirm if its still an issue?

**Comment by Jonatz** [comment]
@yaichenbaum Yes, I can confirm that. I'm on version 3.4.95.0. It doesn't crash when setting default modes and switching from them to overlay mode manually (I tried really hard :D). There seems to be a small UI glitch, though. When setting the launch mode to focus, the back button bleeds into the title bar (see screeshot). Thanks for your work! 
![quickpadfeedback](https://user-images.githubusercontent.com/17417041/72280564-e4a04a80-3638-11ea-8ffc-03313f241458.png)

**Comment by yaichenbaum** [comment]
That's great, I already created an issue #319 but decided to ship what was fixed already as opposed to keeping you waiting for longer 😊
