### ISSUE TITLE
Text Aligning Buttons Overlap

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#346]
**Describe the bug**
The text-align buttons are fucked up.

**To Reproduce**
1. Make a new file
2. write some text
3. use the align text buttons and click each one
4. leave it alone

**Expected behavior**
The button of the selected aligning should be highlighted.

**Desktop (please complete the following information):**
 - OS Version: Win 10 1909
 - App version: 4.3.97.0

**Does It Occur on restart**
Yes

**Comment by yaichenbaum** [comment]
@diligamer Thank you for reporting this issue, it should already be fixed in the `develop` branch and as soon as everything in that branch is stable it will be released.

**Comment by diligamer** [comment]
:shipit:

**Comment by yaichenbaum** [comment]
@diligamer The update is now in certification, please reopen this issue if you find its still a problem in 4.4.0.
