### ISSUE TITLE
NotePad/ Wordpad File Corruption

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#352]
**Describe the bug**
Files created in the former get corrupted. Opening RTF Files gives an error from Microsoft word.

**To Reproduce**
1. Make a file through the former
2. View It In QuickPad

**Expected behavior**
The File Should be viewable normally.

**Desktop (please complete the following information):**
 - OS: Win10 1909 18363.657
 - App version: 4.3.97.0

**Comment by diligamer** [comment]
For clarification, The 'Former' Is WordPad/NotePad. And The Corruption shows up as question marks in rhombus

**Comment by sharpninja** [comment]
Is this happening from HEAD of develop branch, or what's in the store?

**Comment by diligamer** [comment]
The app from the store

**Comment by yaichenbaum** [comment]
@diligamer I am not able to reproduce this issue, can you check if you still run into this when 4.4.0 rolls out?

**Comment by diligamer** [comment]
This Is Fixed Now, No Worries

**Comment by yaichenbaum** [comment]
@diligamer Thank you for letting us know.
