### ISSUE TITLE
Crashing On Launch

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#384]
**Describe the bug**
The App Gives up when launched

**To Reproduce**
1. Launch Quickpad

**Expected behavior**
It should launch

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 2004 19569.1000
 - App version: Undefined

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Comment by yaichenbaum** [comment]
Can you try resetting the app?

**Comment by diligamer** [comment]
Tried Reset and Uninstall. That didn't work.

**Comment by diligamer** [comment]
Here is the Event Viewer Error.
`Faulting application name: QuickPad.UI.exe, version: 1.0.0.0, time stamp: 0x5e52b263
Faulting module name: KERNELBASE.dll, version: 10.0.19569.1000, time stamp: 0xa6e2770a
Exception code: 0x00001007
Fault offset: 0x00000000000c46a3
Faulting process id: 0x2794
Faulting application start time: 0x01d5f21a2d4fac2c
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t\QuickPad.UI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 32cba28b-4f21-4919-84b7-5944ce934804
Faulting package full name: 49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App`

For Note, I Use Windows Insider

**Comment by yaichenbaum** [comment]
This seems to be caused by an error in the SDK, I am on 19569 and don't have the issue so it could be there is a fix that you haven't gotten yet.
@sharpninja Is there anything @diligamer can do to resolve this, or do we need to implement advanced logging to find out where the error is?

**Comment by sharpninja** [comment]
I think logging is going to be required.
________________________________

**Comment by diligamer** [comment]
**Error:**
```Faulting application name: QuickPad.UI.exe, version: 1.0.0.0, time stamp: 0x5e52b263
Faulting module name: KERNELBASE.dll, version: 10.0.19569.1000, time stamp: 0xa6e2770a
Exception code: 0x00001007
Fault offset: 0x00000000000c46a3
Faulting process id: 0x43a4
Faulting application start time: 0x01d5f254513726fe
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t\QuickPad.UI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: bc74e705-589c-461a-b15f-2073283a6760
Faulting package full name: 49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App```

**Info From Windows:**
```Fault bucket 2293383925993600479, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 49306atecsolution.QuickPad_4.4.1.0_x64__et10x9a9vyk8t
P2: praid:App
P3: 1.0.0.0
P4: 5e52b263
P5: KERNELBASE.dll
P6: 10.0.19569.1000
P7: a6e2770a
P8: 00001007
P9: 00000000000c46a3
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER39F8.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B12.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B32.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20200227 1 Event Collector_0_inject.etl
\\?\C:\Users\darom\AppData\Local\Temp\WER3B72.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\Users\darom\AppData\Local\Temp\WER3B73.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B6F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3B8F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_49306atecsolutio_2a6eb77a86dd9f371cbe9231ed3c2975b34937_a6d5331c_15f5b8ae-d83d-4ef8-906d-1520c492a40d

Analysis symbol: 
Rechecking for solution: 0
Report Id: bc74e705-589c-461a-b15f-2073283a6760
Report Status: 2147487744
Hashed bucket: ad274b1851142bfdffd3bc87a27075df
Cab Guid: 0```

I Hope these logs help

**Comment by sharpninja** [comment]
Unfortunately without a stack trace it doesn't add much.  We have seen random WinRT errors that cause exceptions in the Kernal, but they typically go away after updates to Windows.  I am going to have to put a ton of logging into the app to figure out which line of code is crashing inside the kernal.

**Comment by diligamer** [comment]
> Unfortunately without a stack trace it doesn't add much. We have seen random WinRT errors that cause exceptions in the Kernal, but they typically go away after updates to Windows. I am going to have to put a ton of logging into the app to figure out which line of code is crashing inside the kernal.

This Also Occurs with Files UWP

**Comment by yaichenbaum** [comment]
The issue with Files UWP is different than the one here. This one is caused by an SDK issue, while the Files UWP one is something else.
Unless the issue is fixed for you with Quick Pad, I will be keeping this open to continue tracking it until it's fixed.

**Comment by diligamer** [comment]
> The issue with Files UWP is different than the one here. This one is caused by an SDK issue, while the Files UWP one is something else.
> Unless the issue is fixed for you with Quick Pad, I will be keeping this open to continue tracking it until it's fixed.

From What I Can Understand, It seems like the app is crashing the kernel

**Comment by yaichenbaum** [comment]
That is the case here, the issue with Files UWP was actually fixed and an update for it is currently in certification in the store.

**Comment by diligamer** [comment]
It Seems Like Some Code In The Kernel Has Changed. Read The Changelog (And Maybe The Docs) For The Specific Build.

**Comment by yaichenbaum** [comment]
There has been a couple of updates to Windows since this issue was opened, is this still an issue?

**Comment by diligamer** [comment]
Yes, I Am Using 19603.1000 Build 2004 Or 19603.rs_prerelease.200403-1523.

**Comment by sharpninja** [comment]
Try resetting the app again since last update to Windows.

**Comment by diligamer** [comment]
> Try resetting the app again since last update to Windows.

Thanks, This Fixes It!
