### ISSUE TITLE
Basic Line Numbering

### ISSUE THREAD

**Issue by duke7553** [UWPCommunity/Quick-Pad#393]
**Describe the solution you'd like**
Add numbers for each line-ascending along the left side of the app as an optional setting.

**Describe alternatives you've considered**
Not applicable

**Additional context**
Other notepad apps have this functionality.

**Comment by yaichenbaum** [comment]
This will be a nice addition, but we need to think it through. The reason I held off on this is as soon as line numbering is added, requests will start coming for syntax highlighting as well. The goal is to keep Quick Pad as simple as possible. That being said, this can be kept open for discussion to see if it is something Quick Pad users really want.

**Comment by duke7553** [comment]
Good idea. I'll post some of my **untested** code below as a reference implementation instead. (For how it _could_ be done)
```
private void UpdateLineNumbers(string documentText)
        {
            int numLines = 1;
            string buffer = "";
            TextBlock textFormattedWidthChecker = new TextBlock();
            textFormattedWidthChecker.FontSize = LineNumbersList.FontSize;

            foreach(char c in documentText)
            {
                if (c.Equals('\n'))
                {
                    textFormattedWidthChecker.Text = buffer;
                    var formattedWidth = textFormattedWidthChecker.ActualWidth;
                    if(formattedWidth > (Window.Current.Bounds.Width - LineNumbersList.Width))
                    {
                        double wrappedRows = int.Parse(Math.Round(formattedWidth / (Window.Current.Bounds.Width - LineNumbersList.Width)).ToString());
                        for (int x = 0; x < wrappedRows; x++)
                        {
                            Numbers.Add(" ");
                        }
                    }

                    buffer = "";
                    Numbers.Add(numLines.ToString());
                    numLines++;

                }
                else
                {
                    buffer.Append(c);
                }
            }
        }

        public ObservableCollection<string> Numbers { get; } = new ObservableCollection<string>();
```

Essentially, when it's appropriate to update the line numbers, we should compare the width of the text (if it were on a single line) to the width of space available. This should tell us how many lines were wrapped. The wrapped lines should not include a line number, but rather an empty space.

**Comment by duke7553** [comment]
The newly-filled collection of `Numbers` must then be bound to a vertical strip in the GUI. (Probably a ListView-derived control)

**Comment by yaichenbaum** [comment]
@duke7553 Thank you for sharing it! @sharpninja is working on a code editor based on Quick Pad so this might be helpful for him.
