### ISSUE TITLE
iOS And Android Design Protoype

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#401]
![Concept](https://user-images.githubusercontent.com/32780515/77650296-53284f80-6f7c-11ea-8297-0759d7682ac8.png)

This Is Just A Concept, Any Thoughts?

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/77651150-bf865d00-6f42-11ea-9a38-e5bd2b6eb96d.png)

This is just a small sneak-peek of what we are planning 😉

**Comment by diligamer** [comment]
Here are some features to consider:

* Recent Files Area As Homepage

* Removing The Topbar Accent

**Comment by yaichenbaum** [comment]
Recent Files will be the home page. Can you explain what you mean by "Removing The Topbar Accent"?

**Comment by diligamer** [comment]
The Blue Should Be removed

**Comment by yaichenbaum** [comment]
The blue is just the accent color. I am pretty sure that newer versions of Android will let you change that.

**Comment by diligamer** [comment]
The Material Theming "spec" (The Native Android Design) Doesn't Have Topbar Accents

**Comment by diligamer** [comment]
This issue is closed because it is uncessary
