### ISSUE TITLE
Make Quickpad Similar To Wordpad

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#403]
This would be implemented by adding

* Rulers
* Ribbon (File, Home, View)
* FIle Menu 
* White Text Background (App UI Is Still Dark)
* Paper Like (centered)
* Zooming Functions And The Respective Buttons
* Page Setup
* Multiple Pages If Document Is Out Of Margin
* Add Image, Date, Drawing And Object Insertions 

![image](https://user-images.githubusercontent.com/32780515/78330348-765e8a80-758c-11ea-9ae1-cf7e3378d242.png)

![image](https://user-images.githubusercontent.com/32780515/78330367-7f4f5c00-758c-11ea-89e0-41ea045431a5.png)

![image](https://user-images.githubusercontent.com/32780515/78330382-8a09f100-758c-11ea-9ff5-90550a24c423.png)

**Comment by yaichenbaum** [comment]
I am thinking of working on another app with more features, Quick Pad is supposed to have a more basic set like Notepad.

**Comment by diligamer** [comment]
Isn't QuickPad  Both A RTF and TXT Editor

**Comment by yaichenbaum** [comment]
It is both, but the main focus is txt files, for example, the default mode when installing the app is Classic Mode. The default file type is txt. I view RTF support as a bonus feature, but not enough to focus on additional color support and making it similar to Wordpad. Another issue is the RichEditBox control is pretty buggy and wouldn't provide for a great experience as a fully-featured rich text editor. After WinUI 3 is released (still a couple of months away) then some of the issues will likely be fixed. When that happens I will look into creating a separate more rich text focused app.

**Comment by diligamer** [comment]
I Am Seeing A Ribbon And Zooming Is Only Possible Right Now. Can We Narrow To That Instead?

**Comment by yaichenbaum** [comment]
A ribbon would be a major shift of direction for Quick Pad that I do not want to do. Zooming should already be implemented though.

**Comment by yaichenbaum** [comment]
Closing since there are no plans to make Quick Pad more like Wordpad.
