### ISSUE TITLE
Branding The Three Versions

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#404]
Since @yaichenbaum Is Working On An RTF Focused Version, And @sharpninja Is Working On A Code Editor Version, I Think We Need A Naming System For The Trio.

Currently, OneNote, WordPad, NotePad And Sticky Notes are taken.

Here Is The System:

* The TXT Focused (Quick Pad) → TextPad (Brings #1, Removes RTF Functionality)
* The RTF Focused (@yaichenbaum's Version) → DocPad (Removes TXT Functionality, Brings #402, #1 And #403)
* The Code Focused (@sharpninja's Version) → CodePad (Removes DocPad And TextPad Functionality, Brings #393 And Tabs And Drops Non-code based functions)

Icon System: 
* CodePad → The Current Icon But With VSCode's or VStudio's Accent Color
* TextPad → Same Icon As Now
* DocPad → Same icon but with A Picture In it (In the gradient area)

Extras:
Maybe Add Tabs To All Versions? 🤔

**Comment by yaichenbaum** [comment]
I wouldn't put them all together since they are three separate apps. There are plans for tabs in Quick Pad however there is no timeline.

**Comment by diligamer** [comment]
No, They Are Still Separate But have Similar names (*Pad)

**Comment by diligamer** [comment]
http://codepad.org/ Oh No

**Comment by yaichenbaum** [comment]
Closing this issue since right now the plan is to keep making incremental tweaks to the app, rather then shifts in the target audience.

**Comment by diligamer** [comment]
Make Different Versions Like This Issue Says For Each Target Audimce

**Comment by sharpninja** [comment]
I have already been asked by Yair to rename Quick-Code, so that's already something I intend to do.

**Comment by diligamer** [comment]
CodePad Sounds Better In My Opinion

**Comment by diligamer** [comment]
This Issue Is For Naming And Icons Of The Different Apps
