### ISSUE TITLE
Selection screen to select document type.

### ISSUE THREAD

**Issue by Senko-Dev** [UWPCommunity/Quick-Pad#418]
Currently, Quick Pad can create and edit RTF, MD, and TXT files, but the RTF and MD capability is not fully known by the UI. It would also be great because we can easily create documents. This page would also act like the launch window in visual studio, allowing users to open recent files and pin their most used files, the right pane is where the `create new document` area would be. 

![image](https://user-images.githubusercontent.com/32780515/82742103-5cf2e700-9d62-11ea-80e2-93b7df937274.png)

**Comment by yaichenbaum** [comment]
@Senko-Dev Thank you for opening this issue, the vision for Quick Pad is to be a simple text editor and not a full blown code editor like Visual Studio. There are no plans to make these changes in the future so I will be closing this issue.
