### ISSUE TITLE
Cannot save rtf files

### ISSUE THREAD

**Issue by jean3x7** [UWPCommunity/Quick-Pad#424]
When i try to save rtf files, quickpad create empty file and freeze.

**Comment by DonLuke25** [comment]
Same, I can't save .txt files!!

**Comment by yaichenbaum** [comment]
Is this issue with saving existing files or is it only when saving new files?

**Comment by SubjunctiveQuaver** [comment]
Existing files included for me.

**Comment by DonLuke25** [comment]
> Is this issue with saving existing files or is it only when saving new files?

Unfortunately both. When saving a new file, it creates the file, but won't save anything into it.

**Comment by jean3x7** [comment]
> Is this issue with saving existing files or is it only when saving new files?

Occurred with new files and save existing files, txt and rtf.

**Comment by yaichenbaum** [comment]
#425 Includes a potential fix for this issue, is anyone able to help out by testing the pull request and checking if it fixes the issue?

**Comment by yaichenbaum** [comment]
Quick Pad 4.4.4 is now available in the Microsoft Store.
