### ISSUE TITLE
unable to save

### ISSUE THREAD

**Issue by B3HI13** [UWPCommunity/Quick-Pad#427]
**Describe the bug**

if u create a text file with right click on desktop, the entered content does not save. even save btn in the app does not work. ctrl + s does not work. 
pls fix it. the app is very good.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS Version:  
Windows 10 1909
- App version:  
4.4.3.0
**Additional context**

**Comment by yaichenbaum** [comment]
@B3HI13 This issue was fixed with the 4.4.4 issue, you can get the update through the Microsoft Store.
