### ISSUE TITLE
Ability to force a language, separate from system language settings

### ISSUE THREAD

**Issue by PhilLB1239** [UWPCommunity/Quick-Pad#67]
As described by the title, the user should have the ability to force a specific translation of Quick Pad that is available in the specific version from the settings page.

Not only it will bring more choices to the end user that works with multiple languages, it will also be a convenient feature for current translators of Quick Pad, including me, since some of us works with a different system language and I personally don't want to constantly change my system language for each build.

**Comment by yaichenbaum** [comment]
1. Settings dialog closes when changing the language.
2. Change does not take affect right away, it might need a few milliseconds delay before the code runs...

**Comment by yaichenbaum** [comment]
@ray1997 the message comes up telling you to restart but does not apply the change when you actually reopen the app for some reason.

**Comment by ray1997** [comment]
@yaichenbaum I just forget to send a setting back to a setting storage 🤦‍♂️

**Comment by yaichenbaum** [comment]
Issue resolved.
