### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#73]
A user requested RTL support. We should add this as soon as possible.

**Comment by sharpninja** [comment]
What needs to be done that Windows doesn't already do?

**Comment by yaichenbaum** [comment]
I think the user wanted the option to toggle between them without changing any settings on Windows.

**Comment by sharpninja** [comment]
Unless you can do that on the root form and it propagate through the whole tree, that's going to be a very big mess.
________________________________

**Comment by yaichenbaum** [comment]
Can't we set the flow direction?

**Comment by yaichenbaum** [comment]
I don't think we will end up doing this setting in the end, the only real option is to set the text alignment which the user can do themselves.

**Comment by diligamer** [comment]
@yaichenbaum I highly recommend closing the issue.

**Comment by yaichenbaum** [comment]
@diligamer It already is closed 😕

**Comment by diligamer** [comment]
> @diligamer It has been closed for a few weeks already 😕

I meant lock it.

**Comment by yaichenbaum** [comment]
@diligamer Can you explain the benefits of doing that?

**Comment by diligamer** [comment]
prevent people from talking in a closed issue.
