### ISSUE TITLE
Popup on first launch asking user to choose what mode to use the app in

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#84]
Basic concept 
![image](https://user-images.githubusercontent.com/39923744/63553012-38ce5500-c507-11e9-867d-28709e7d5dcf.png)

**Comment by themoiFR** [comment]
How can I help doing something ? I am really interested by this project 😁

**Comment by yaichenbaum** [comment]
@themoiFR thanks! There is a lot of work to do, mainly fixing bugs and weird behaviors throughout the app, do you ave any programming experience?

**Comment by themoiFR** [comment]
I am in a French engineering school. I participate in a c# project last year and recently (this week end) I made a wpf application in c# using visual studio to program a circuit board. I like coding and I try to make my code a clear as possible and with a good quality (learned a lot about code quality in my school). So yes I have an experience

**Comment by yaichenbaum** [comment]
We are in about to start rewriting the app and at I will be creating tasks for what needs to be done and I will label them rewrite, if any of the tasks are something you want to do then let us know on the issue.

**Comment by themoiFR** [comment]
Okay, I will wait for those new tasks, thanks a lot

**Comment by yaichenbaum** [comment]
@themoiFR there are several tasks labeled refactor, feel free to pick any of them.

**Comment by themoiFR** [comment]
> @themoiFR there are several tasks labeled refactor, feel free to pick any of them.
I cloned the project to vs2019 but i have a problem : When I build the project, I have an error I haven't seen before : No certificate found with the supplied thumbprint: ...
Can you help me ?

**Comment by yaichenbaum** [comment]
First of all make sure you are on the refactor branch, second you can follow the solution [here](https://developercommunity.visualstudio.com/content/problem/612872/create-test-certificate-option-missing-from-uwp-sd.html
) to create a certificate.

**Comment by themoiFR** [comment]
ok that work thanks

**Comment by yaichenbaum** [comment]
@themoiFR Are you still available to help with the rewrite?

**Comment by themoiFR** [comment]
> @themoiFR Are you still available to help with the rewrite?

Yes I am

**Comment by yaichenbaum** [comment]
@themoiFR Ok, how about just going through the app and finding whats not working yet, when you find something first create and issue in case someone else is already working on it.
