### ISSUE TITLE
Sync settings with Microsoft account

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#85]
Useful for someone with more then one device for them to be able to keep the customization options they choose, as well as helpful if they reset the app or move to a new device.
Reminder to myself that I have a good method to use.

**Comment by ray1997** [comment]
We can easily move setting on local setting to store on `ApplicationData.Current.RoamingSettings` and it will sync across account.

https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#roaming-data

Or is there another way you want to use?

**Comment by yaichenbaum** [comment]
There is another way I want to use @Arlodotexe has something he wrote and offered to let us use it as well.

**Comment by yaichenbaum** [comment]
@sharpninja I believe this is working in the rewrite?

**Comment by sharpninja** [comment]
Yes, the settings are stored in your Microsoft account and updated as you change them.
